apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user.fullname" . }}-configmap
data:
  db-name: {{ index .Values.configmap "db-name" }}
  db-url: {{ index .Values.configmap "db-url" }}
  cache-url: {{ index .Values.configmap "cache-url" }}