apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user.fullname" . }}-deployment
  labels:
    {{- include "user.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "user.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: user-configmap
                key: db-url
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: user-configmap
                key: db-name
          - name: CACHE_URL
            valueFrom:
              configMapKeyRef:
                name: user-configmap
                key: cache-url
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
