server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    co.fastcampus.auth0: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: <Auth0 Client ID>
            client-secret: <Auth0 Client Secret>
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://<Auth0 Issuer URI>/
