apiVersion: v1
kind: Service
metadata:
  name: vault-data-security
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: vault-data-security
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-data-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-data-security
  template:
    metadata:
      labels:
        app: vault-data-security
    spec:
      containers:
        - name: vault-data-security
          image: <AWS ECR URL>/vault:1.0
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080