apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentracingwas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentracingwas
  template:
    metadata:
      labels:
        app: opentracingwas
    spec:
      containers:
        - name: opentracingwas
          image: <AWS ECR URL>/opentracingwas:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: opentracingwas
spec:
  selector:
    app: opentracingwas
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP