# Default values for order.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: <AWS ECR URL>/authorservice
  pullPolicy: IfNotPresent
  tag: "1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  db-name: "mapstruct_demo"
  db-url: "mysql"

secret:
  password: "cGFzc3dvcmQK"
  username: "cm9vdAo="